### PR TITLE
Partial output & Compilation error hints

### PR DESCRIPTION
**Pull request by thepieterdc**
### ~**!HOLD:  This may not be merged until https://github.ugent.be/dodona/dodona/issues/1032 is either fixed or is confirmed as not being a bug, as it imposes an authorization risk!**~

(Rewrite of #13), using the partial output scheme.

**Compilation error in submitted code:**
compile-submission

**Compilation error in workdir/tests:**
Staff/zeus gets a compilation log (just like the student sees when there's a compilation error in their code), but this log is hidden for students as it's not their code.
compile-tests

**Compilation error/warning hints**
Support for more error/warning hints can be added as new errors and warnings arise by students. If no hint is found, the annotation shows the first line of the java compiler (cleaned) and the hint-message is not added in the testcase. Currently these hints are built in:
- (Error) Wrong class name
- (Warning) Use of raw types with generic classes

**Remarks:**
- Reported memory usage seems a bit high, not sure if this is actually correct since it's sometimes zero, should be verified.
- Multi-language support could be very easily added in, it's only Dutch for now.

_[Original pull request](https://github.ugent.be/dodona/judge-java/pull/15) by @thepieterdc on Wed Apr 10 2019 at 00:58._
_Merged by @ninewise on Thu Apr 25 2019 at 09:52._

### CODE REVIEW

**Comment by thepieterdc** [comment]
**Updated output for submissions that failed to compile:**
image


**Updated output for students when tests fail to compile:**
image


_[Original comment](https://github.ugent.be/dodona/judge-java/pull/15#issuecomment-88054) by @thepieterdc on Wed Apr 10 2019 at 13:09._

**Review by bmesuere — APPROVED** [review]
If it's ok for @ninewise, it's ok for me.

_[Original approval](https://github.ugent.be/dodona/judge-java/pull/15#pullrequestreview-16698) by @bmesuere on Wed Apr 10 2019 at 13:41._

**Review by ninewise — CHANGES_REQUESTED** [review]
_[Original change request](https://github.ugent.be/dodona/judge-java/pull/15#pullrequestreview-16712) by @ninewise on Wed Apr 10 2019 at 16:15._

**Comment by thepieterdc** [comment]
I have applied all but two requested changes (discussion is still open).

_[Original comment](https://github.ugent.be/dodona/judge-java/pull/15#issuecomment-88089) by @thepieterdc on Wed Apr 10 2019 at 22:26._

**Comment by thepieterdc** [comment]
All remarks should be fixed now.

_[Original comment](https://github.ugent.be/dodona/judge-java/pull/15#issuecomment-88113) by @thepieterdc on Thu Apr 11 2019 at 16:17._

**Review by ninewise — CHANGES_REQUESTED** [review]
_[Original change request](https://github.ugent.be/dodona/judge-java/pull/15#pullrequestreview-16776) by @ninewise on Thu Apr 11 2019 at 17:15._

**Comment by ninewise** [comment]
Merged after re-rebase in 18be4b2bf54b532d62f5fcc0d7dd7b5684d7c7a6.

_[Original comment](https://github.ugent.be/dodona/judge-java/pull/15#issuecomment-88650) by @ninewise on Thu Apr 25 2019 at 09:52._

**Pull request closed without merging**
