### PR TITLE
Friendly compilation errors

### PR DESCRIPTION
**Pull request by thepieterdc**
When the submitted code has an incorrect name, a custom message is displayed instead of the usual Java compiler output. This can be useful for students from other courses that have never seen a compiler and are clueless about what their mistake is.

More messages could be added along the way, maybe this behaviour could be toggled on/off using the `config.json` file in the exercise, similar to the running time/memory usage limits.

_[Original pull request](https://github.ugent.be/dodona/judge-java/pull/13) by @thepieterdc on Sun Apr 07 2019 at 21:41._
_Merged by @thepieterdc on Wed Apr 10 2019 at 01:01._

### CODE REVIEW

**Review by ninewise — COMMENTED** [review]
I agree this message is useful; but the original error message should still be shown. They might not be used to compiler errors yet, but it never hurts to expose them.

_[Original review](https://github.ugent.be/dodona/judge-java/pull/13#pullrequestreview-16586) by @ninewise on Sun Apr 07 2019 at 22:52._

**Comment by bmesuere** [comment]
We are not a compiler and should offer as much feedback as possible. The raw output can indeed still be shown, but if we can make it clearer what goes wrong, why not?

Other suggestions:
- list the number of errors or warnings (also) at the top
- better separate the errors. Right now it's hard to see where 1 ends and the next error starts
- replace the summary "in submitted code" with "*x* errors"

_[Original comment](https://github.ugent.be/dodona/judge-java/pull/13#issuecomment-87938) by @bmesuere on Sun Apr 07 2019 at 23:15._

**Comment by thepieterdc** [comment]
> We are not a compiler and should offer as much feedback as possible. The raw output can indeed still be shown, but if we can make it clearer what goes wrong, why not?
> 
> Other suggestions:
> 
> * list the number of errors or warnings (also) at the top
> * better separate the errors. Right now it's hard to see where 1 ends and the next error starts
> * replace the summary "in submitted code" with "_x_ errors"

I have implemented these suggestions, except from the second one, since that turned out to be a bit tricky. However the current output looks like this. This could be further augmented to support both Dutch/English/(Korean?) but I guess it's a good start.

```json
{
 "accepted": false,
 "status": "compilation error",
 "description": "1 fout",
 "groups": [
  {
   "description": "Compiler",
   "groups": [
    {
     "accepted": false,
     "messages": [
      {
       "format": "plain",
       "description": "Je oplossing kon niet worden gecompileerd, de compiler rapporteerde 1 fout en 2 waarschuwingen:"
      },
      {
       "format": "code",
       "description": "De ingediende klasse heeft een foute naam. De klasse hoort als naam \"Team\" te hebben, jouw klasse heeft als naam \"NotTeam\"."
      },
      {
       "format": "code",
       "description": "Team.java:3: error: class NotTeam is public, should be declared in a file named NotTeam.java\npublic class NotTeam {\n       ^\nTeam.java:4: warning: [rawtypes] found raw type: List\n\tpublic List test;\n\t       ^\n  missing type arguments for generic class List<E>\n  where E is a type-variable:\n    E extends Object declared in interface List\nTeam.java:5: warning: [rawtypes] found raw type: List\n\tpublic List test2;\n\t       ^\n  missing type arguments for generic class List<E>\n  where E is a type-variable:\n    E extends Object declared in interface List"
      }
     ]
    }
   ]
  }
 ]
}
```

When the tests or workdir cannot be compiled, the pretty feedback is not applied and a message is shown to the student, indicating that the teacher should be contacted:

```json
{
 "accepted": false,
 "status": "compilation error",
 "description": "in tests",
 "groups": [
  {
   "description": "Compiler",
   "groups": [
    {
     "accepted": false,
     "messages": [
      {
       "format": "plain",
       "description": "De tests van deze opgave bevatten een fout, contacteer de lesgever."
      },
      {
       "format": "code",
       "description": "Team.java:5: error: cannot find symbol\n\tprivate final Strina[] members;\n\t              ^\n  symbol:   class Strina\n  location: class Team\nTeam.java:6: error: cannot find symbol\n\tprivate Strinb name;\n\t        ^\n  symbol:   class Strinb\n  location: class Team\n2 errors"
      }
     ]
    }
   ]
  }
 ]
}
```

_[Original comment](https://github.ugent.be/dodona/judge-java/pull/13#issuecomment-87940) by @thepieterdc on Mon Apr 08 2019 at 01:53._

**Comment by ninewise** [comment]
> We are not a compiler and should offer as much feedback as possible. The raw output can indeed still be shown, but if we can make it clearer what goes wrong, why not?

We might not be a compiler, but we are teaching the students to work with a compiler. A message clarifying a misnamed class is certainly useful, because it originates in something the students can't see: the filename of their submission in the docker. Compilation errors in their own code should be kept as-is, except maybe some fancy layouting.

> This could be further augmented to support both Dutch/English/(Korean?) but I guess it's a good start.

Language support would be nice, but something for another PR. IIRC we receive the language setting on stdin, along with the rest of the configuration.

> When the tests or workdir cannot be compiled, the pretty feedback is not applied and a message is shown to the student, indicating that the teacher should be contacted

We should keep the compilation errors in the tests/workdir, but add a `"permission": "teacher"` to it. Then the teacher can still see what went wrong when he views the submission.


_[Original comment](https://github.ugent.be/dodona/judge-java/pull/13#issuecomment-87945) by @ninewise on Mon Apr 08 2019 at 09:47._

**Comment by thepieterdc** [comment]
> We should keep the compilation errors in the tests/workdir, but add a "permission": "teacher" to it. Then the teacher can still see what went wrong when he views the submission.

This is implemented in https://github.ugent.be/dodona/judge-java/pull/13/commits/cbf522ac0efca0db3a343a69d277289336be3a48 Now I'm trying to split the different compile messages.

_[Original comment](https://github.ugent.be/dodona/judge-java/pull/13#issuecomment-87991) by @thepieterdc on Tue Apr 09 2019 at 13:29._

**Comment by thepieterdc** [comment]
Continues in #15. All of the suggestions mentioned in this pull request were implemented.

_[Original comment](https://github.ugent.be/dodona/judge-java/pull/13#issuecomment-88033) by @thepieterdc on Wed Apr 10 2019 at 01:01._

**Pull request closed without merging**
